export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//styles
const mainBodyStyle={
  display: 'block',
  margin: 0,
  marginTop: 0,
  marginRight: 0,
  marginBottom: 0,
  marginLeft: 0,
  height: "100vh",
  width: "100%",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={mainBodyStyle}>{children}</body>
    </html>
  )
}
